apiVersion: v1
kind: Service
metadata:
  name: edgewave-backend
  namespace: edgewave
spec:
  selector:
    app: edgewave-backend
    color: blue
    track: blue
  ports:
    - port: 8080
      targetPort: 8000
      protocol: TCP
