apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgewave-frontend-green
  namespace: edgewave
  labels:
    app: edgewave-frontend
    color: green
    track: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edgewave-frontend
      track: green
  template:
    metadata:
      labels:
        app: edgewave-frontend
        color: green
        track: green
    spec:
      containers:
        - name: edgewave-frontend
          image: gauravchile/edgewave:frontend-green-v1.0.0
          ports:
            - containerPort: 80
