apiVersion: v1
kind: Service
metadata:
  name: edgewave-frontend
  namespace: edgewave
spec:
  selector:
    app: edgewave-frontend
    color: blue
    track: blue
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
