apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgewave-frontend-blue
  namespace: edgewave
  labels:
    app: edgewave-frontend
    color: blue
    track: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edgewave-frontend
      track: blue
  template:
    metadata:
      labels:
        app: edgewave-frontend
        color: blue
        track: blue
    spec:
      containers:
        - name: edgewave-frontend
          image: gauravchile/edgewave:frontend-blue-v1.0.0
          ports:
            - containerPort: 80
